### ISSUE TITLE
container doesn t start

### ISSUE THREAD

**Issue by davask** [spujadas/elkx-docker#1] opened 2017-03-21 13:05 UTC
Hi,

I have tested all your troubleshouting techniks and I can t figure out what s wrong.

I try to run under rancher this compose:

```yaml

elkx:
  ports:
  - 5044:5044/tcp
  - 5601:5601/tcp
  - 9200:9200/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPublic
  image: sebp/elkx:520
  volumes:
  - elkx:/var/lib/elasticsearch

```

and I got these logs

```log

3/21/2017 12:22:19 PM * Starting periodic command scheduler cron
3/21/2017 12:22:19 PM   ...done.
3/21/2017 12:22:19 PM * Starting Elasticsearch Server
3/21/2017 12:22:34 PM   ...fail!
3/21/2017 12:22:37 PMwaiting for Elasticsearch to be up (1/30)
3/21/2017 12:22:38 PMwaiting for Elasticsearch to be up (2/30)
3/21/2017 12:22:39 PMwaiting for Elasticsearch to be up (3/30)
3/21/2017 12:22:40 PMwaiting for Elasticsearch to be up (4/30)
3/21/2017 12:22:41 PMwaiting for Elasticsearch to be up (5/30)
3/21/2017 12:22:43 PMwaiting for Elasticsearch to be up (6/30)
3/21/2017 12:22:44 PMwaiting for Elasticsearch to be up (7/30)
3/21/2017 12:22:45 PMwaiting for Elasticsearch to be up (8/30)
3/21/2017 12:22:46 PMwaiting for Elasticsearch to be up (9/30)
3/21/2017 12:22:47 PMwaiting for Elasticsearch to be up (10/30)
3/21/2017 12:22:48 PMwaiting for Elasticsearch to be up (11/30)
3/21/2017 12:22:49 PMwaiting for Elasticsearch to be up (12/30)
3/21/2017 12:22:50 PMwaiting for Elasticsearch to be up (13/30)
3/21/2017 12:22:51 PMwaiting for Elasticsearch to be up (14/30)
3/21/2017 12:22:52 PMwaiting for Elasticsearch to be up (15/30)
3/21/2017 12:22:53 PMwaiting for Elasticsearch to be up (16/30)
3/21/2017 12:22:54 PMwaiting for Elasticsearch to be up (17/30)
3/21/2017 12:22:55 PMwaiting for Elasticsearch to be up (18/30)
3/21/2017 12:22:56 PMwaiting for Elasticsearch to be up (19/30)
3/21/2017 12:22:57 PMwaiting for Elasticsearch to be up (20/30)
3/21/2017 12:22:59 PMwaiting for Elasticsearch to be up (21/30)
3/21/2017 12:23:00 PMwaiting for Elasticsearch to be up (22/30)
3/21/2017 12:23:01 PMwaiting for Elasticsearch to be up (23/30)
3/21/2017 12:23:02 PMwaiting for Elasticsearch to be up (24/30)
3/21/2017 12:23:03 PMwaiting for Elasticsearch to be up (25/30)
3/21/2017 12:23:04 PMwaiting for Elasticsearch to be up (26/30)
3/21/2017 12:23:05 PMwaiting for Elasticsearch to be up (27/30)
3/21/2017 12:23:07 PMwaiting for Elasticsearch to be up (28/30)
3/21/2017 12:23:08 PMwaiting for Elasticsearch to be up (29/30)
3/21/2017 12:23:09 PMwaiting for Elasticsearch to be up (30/30)
3/21/2017 12:23:09 PMCouln't start Elasticsearch. Exiting.
3/21/2017 12:23:09 PMElasticsearch log follows below.
3/21/2017 12:23:09 PM[2017-03-21T11:19:05,602][INFO ][o.e.n.Node               ] [] initializing ...
3/21/2017 12:23:09 PM[2017-03-21T11:19:06,240][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/sda2)]], net usable_space [374.4gb], net total_space [457.2gb], spins? [possibly], types [ext4]
3/21/2017 12:23:09 PM[2017-03-21T11:19:06,241][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] heap size [1.9gb], compressed ordinary object pointers [true]
3/21/2017 12:23:09 PM[2017-03-21T11:19:06,418][INFO ][o.e.n.Node               ] node name [ZVc9ZHX] derived from node ID [ZVc9ZHX3RROOSsuo2ebnaw]; set [node.name] to override
3/21/2017 12:23:09 PM[2017-03-21T11:19:06,425][INFO ][o.e.n.Node               ] version[5.2.0], pid[48], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/3.13.0-93-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
3/21/2017 12:23:09 PM[2017-03-21T11:20:17,764][INFO ][o.e.n.Node               ] [] initializing ...
3/21/2017 12:23:09 PM[2017-03-21T11:20:21,448][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/sda2)]], net usable_space [374.4gb], net total_space [457.2gb], spins? [possibly], types [ext4]
3/21/2017 12:23:09 PM[2017-03-21T11:20:21,448][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] heap size [1.9gb], compressed ordinary object pointers [true]
3/21/2017 12:23:09 PM[2017-03-21T11:20:21,578][INFO ][o.e.n.Node               ] node name [ZVc9ZHX] derived from node ID [ZVc9ZHX3RROOSsuo2ebnaw]; set [node.name] to override
3/21/2017 12:23:09 PM[2017-03-21T11:20:21,585][INFO ][o.e.n.Node               ] version[5.2.0], pid[46], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/3.13.0-93-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
3/21/2017 12:23:09 PM[2017-03-21T11:21:30,390][INFO ][o.e.n.Node               ] [] initializing ...
3/21/2017 12:23:09 PM[2017-03-21T11:21:30,930][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/sda2)]], net usable_space [374.4gb], net total_space [457.2gb], spins? [possibly], types [ext4]
3/21/2017 12:23:09 PM[2017-03-21T11:21:30,931][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] heap size [1.9gb], compressed ordinary object pointers [true]
3/21/2017 12:23:09 PM[2017-03-21T11:21:31,197][INFO ][o.e.n.Node               ] node name [ZVc9ZHX] derived from node ID [ZVc9ZHX3RROOSsuo2ebnaw]; set [node.name] to override
3/21/2017 12:23:09 PM[2017-03-21T11:21:31,204][INFO ][o.e.n.Node               ] version[5.2.0], pid[46], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/3.13.0-93-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,287][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [aggs-matrix-stats]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,288][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [ingest-common]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,288][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-expression]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,290][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-groovy]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,290][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-mustache]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,291][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-painless]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,291][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [percolator]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,291][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [reindex]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,291][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [transport-netty3]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,292][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [transport-netty4]
3/21/2017 12:23:09 PM[2017-03-21T11:21:47,293][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded plugin [x-pack]
3/21/2017 12:23:09 PM[2017-03-21T11:22:48,775][INFO ][o.e.n.Node               ] [] initializing ...
3/21/2017 12:23:09 PM[2017-03-21T11:22:49,294][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/sda2)]], net usable_space [374.4gb], net total_space [457.2gb], spins? [possibly], types [ext4]
3/21/2017 12:23:09 PM[2017-03-21T11:22:49,295][INFO ][o.e.e.NodeEnvironment    ] [ZVc9ZHX] heap size [1.9gb], compressed ordinary object pointers [true]
3/21/2017 12:23:09 PM[2017-03-21T11:22:49,457][INFO ][o.e.n.Node               ] node name [ZVc9ZHX] derived from node ID [ZVc9ZHX3RROOSsuo2ebnaw]; set [node.name] to override
3/21/2017 12:23:09 PM[2017-03-21T11:22:49,467][INFO ][o.e.n.Node               ] version[5.2.0], pid[46], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/3.13.0-93-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,558][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [aggs-matrix-stats]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,559][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [ingest-common]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,559][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-expression]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,568][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-groovy]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,568][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-mustache]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,578][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [lang-painless]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,579][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [percolator]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,579][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [reindex]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,579][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [transport-netty3]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,579][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded module [transport-netty4]
3/21/2017 12:23:09 PM[2017-03-21T11:23:04,583][INFO ][o.e.p.PluginsService     ] [ZVc9ZHX] loaded plugin [x-pack]

```

any Idea why elasticsearch is not running ?

**Comment by spujadas** [comment] 2017-03-22 19:55
Just acknowledging the issue, will look into this over the weekend.

**Comment by spujadas** [comment] 2017-03-26 13:32
Unfortunately I couldn't reproduce your issue: in my set-up (I'm unfamiliar with Rancher, but did a quick and dirty local installation from scratch anyway) I created a stack with the following service:

	elkx:
	  ports:
	  - 5044:5044/tcp
	  - 5601:5601/tcp
	  - 9200:9200/tcp
	  image: sebp/elkx:520

So same as your YAML file except that I removed `labels` (which Rancher doesn't seem to like in my set-up, so the container won't start at all) and `volumes` (which I didn't want to use just to try to get the container running), and everything is running fine:

![screenshot-localhost 8080 2017-03-26 15-03-27](https://cloud.githubusercontent.com/assets/930566/24331515/1e713582-1236-11e7-95d1-447125b70641.png)

Having said that your logs look fine, so despite the container reporting that it's waiting for ES to start (and ultimately failing and therefore exiting) it does look as though ES did actually (begin to) start properly, so maybe it didn't have enough time to be available within the 30 retries (ES is detected as being available if it responds at http://localhost:9200): in my set-up ES starts within 11 seconds with Rancher compared to 7 with the vanilla Docker.

With all the above in mind, could you try the following:

- Set the `ES_CONNECT_RETRY` to a higher value (default is 30 retries, i.e. expects ES to start within 30 seconds).

- Use the same `docker-compose.yml` that I used in Rancher.

- Start the container using just Docker (without Rancher) to establish a baseline on your set-up.

**Comment by davask** [comment] 2017-03-27 12:06
Hi Sébastien,

 

Thanks for your quick answer.

 

I follow your advises and I had to change the way of versioning the indexes but now it is working much better and this is more portable.

 

I use this docker-compose now :

 

elkx:

  ports:

  - 5044:5044/tcp

  - 5601:5601/tcp

  - 9200:9200/tcp

  environment:

    ES_CONNECT_RETRY: '120'

  image: sebp/elkx:520

  volumes:

  - /dir/to/conf:/dwl/conf

  - /dir/to/export:/dwl/export

 

 

Do you know how can I « expose » the file /etc/elasticsearch/elasticsearch.yml without exposing the rest of the dir /etc/elasticsearch/ ? by expose I mean available on the host to allow me to update that file at will without docker exec -ti <my elkx container> bash ?

 

Best regards

 

 <https://www.linkedin.com/in/davaskweblimited> David Asquiedge -  <http://www.davaskweblimited.com/> davask web ltd.

**Comment by spujadas** [comment] 2017-03-27 19:18
Glad to hear you managed to get everything working!

> Do you know how can I « expose » the file /etc/elasticsearch/elasticsearch.yml without exposing the rest of the dir /etc/elasticsearch/ ? by expose I mean available on the host to allow me to update that file at will without docker exec -ti <my elkx container> bash ?

Yes, within the `volumes` section of your `docker-compose.yml` file, map your local file to the `/etc/elasticsearch/elasticsearch.yml` file in the container (i.e. in the same way as you would expose a directory). See https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume for more on mounting host files with Docker.

**Comment by davask** [comment] 2017-03-27 19:57
I already tried that. It gave me a directory called elasticsearch.yml.


Thks




david asquiedge









On Mon, Mar 27, 2017 at 9:18 PM +0200, "Sébastien Pujadas" <notifications@github.com> wrote:












Glad to hear you managed to get everything working!



Do you know how can I « expose » the file /etc/elasticsearch/elasticsearch.yml without exposing the rest of the dir /etc/elasticsearch/ ? by expose I mean available on the host to allow me to update that file at will without docker exec -ti  bash ?



Yes, within the volumes section of your docker-compose.yml file, map your local file to the /etc/elasticsearch/elasticsearch.yml file in the container (i.e. in the same way as you would expose a directory). See https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume for more on mounting host files with Docker.

**Comment by spujadas** [comment] 2017-03-27 20:07
IIRC, the `elasticsearch.yml` file needs to be created on the host (take [this one](https://raw.githubusercontent.com/spujadas/elk-docker/master/elasticsearch.yml) which is the one included in the image) before you attempt that (otherwise it creates a directory).

**Comment by davask** [comment] 2017-03-27 21:30
I tried that too and it seems that sibblings files and directory are not created when container is startedq, i ll double check tomorrow.

It seems that /etc/elasticsearch/elasticsearch.yml volume is mounted before installation of es, so I m guessing es can t create it and sibblings are not added then.




david asquiedge






From: Sébastien Pujadas

Sent: Monday, 27 March 22:07

Subject: Re: [spujadas/elkx-docker] container doesn t start (#1)

To: spujadas/elkx-docker

Cc: davask, Author



IIRC, the elasticsearch.yml file needs to be created on the host (take this one which is the one included in the image) before you attempt that (otherwise it creates a directory).

**Comment by spujadas** [comment] 2017-03-27 21:36
OK, I'll cross-check that on my side as well.

**Comment by davask** [comment] 2017-03-28 12:20
Hi Sebastien.

 

I need to mount the /var/lib/elasticsearch to my host (after the first initialization) in order to maintain data in case of server reboot and to avoid to restore data each time it happens (doesn t happens a lot but still needed)

 

So far the only solution I have is to boot, make a cp of /var/lib/elasticsearch to retrieve it in another mounted volume in order to extract the volume to my host and recreate this container with this extracted mounted volume.

 

Do you think we could have the /var/lib/elasticsearch to be generated on the host if the host directory is not created (or empty) at first ?

 

I’m thinking it is the same type of issue as the /etc/elasticsearch/elasticsearch.yml

 

Best regards

 

 <https://www.linkedin.com/in/davaskweblimited> David Asquiedge -  <http://www.davaskweblimited.com/> davask web ltd.

**Comment by spujadas** [comment] 2017-03-28 18:42
> I tried that too and it seems that sibblings files and directory are not created when container is startedq, i ll double check tomorrow. It seems that /etc/elasticsearch/elasticsearch.yml volume is mounted before installation of es, so I m guessing es can t create it and sibblings are not added then.

Docker doesn't create or copy the files from the image (or container for that matter) over on the host when the container is started, it's actually the other way around: the `volumes` directive tells Docker which file/directory in the image should be overridden with those on the host.

As a complete example here's what I did on my side (which works).

I created a custom Elasticsearch YAML file (nothing fancy, just the original file with an additional comment at the top of the file), named `/path/to/elasticsearch.x1-custom.yml`, on my host.

I created a custom Docker Compose YAML file, named `elasticsearch.x1-custom.yml` on my host.

	elk:
	  build: .
	  ports:
	    - "5601:5601"
	    - "9200:9200"
	    - "5044:5044"
	  volumes:
	    - /path/to/elasticsearch.x1-custom.yml:/etc/elasticsearch/elasticsearch.yml

I then started the container using this custom file:

    $ docker-compose -f docker-compose.x1-custom-elasticsearch.yml up

If I now look at the `/etc/elasticsearch/elasticsearch.yml` in the container:

	$ docker exec -it elkdocker_elk_1 head /etc/elasticsearch/elasticsearch.yml
	## MY CUSTOM elasticsearch.yml

	# ======================== Elasticsearch Configuration =========================
	#
	# NOTE: Elasticsearch comes with reasonable defaults for most settings.

So the custom `elasticsearch.x1-custom.yml` file is taken into account.

> I need to mount the /var/lib/elasticsearch to my host (after the first initialization) in order to maintain data in case of server reboot and to avoid to restore data each time it happens (doesn t happens a lot but still needed)

Technically you don't need to do that: `/var/lib/elasticsearch` is declared as a volume in the `Dockerfile` so changes within this directory in the container will persist across container restarts and server reboots. (Just to be clear, you should still have a proper backup/restore strategy, e.g. using Elasticsearch's snapshot and restore module.)

> So far the only solution I have is to boot, make a cp of /var/lib/elasticsearch to retrieve it in another mounted volume in order to extract the volume to my host and recreate this container with this extracted mounted volume.
> Do you think we could have the /var/lib/elasticsearch to be generated on the host if the host directory is not created (or empty) at first ?

The `/var/lib/elasticsearch` in the image in empty, so if you want to do something like what you're describing, then create an empty directory on your host (say `/my/es/data`) and use a `volumes` directive in your `docker-compose.yml` to map this directory to `/var/lib/elasticsearch` in the container:

	...
	  volumes:
	    - /my/es/data:/var/lib/elasticsearch

Then ES will initially populate the directory on the host (via the bind-mounted volume), and subsequently use this directory after restarts, which I believe corresponds to your use case.

(Btw, I'm going to go ahead and close this as the original issue has been solved.)

**Closed by spujadas** 2017-03-28 18:42 UTC

**Comment by davask** [comment] 2017-03-28 19:50
Thanks Sébastien,

 

I’ll follow your examples to fit my needs.

 

Thanks again for the help.

 

 <https://www.linkedin.com/in/davaskweblimited> David Asquiedge -  <http://www.davaskweblimited.com/> davask web ltd.
